services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: alitnazari/behkhaan:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    entrypoint:
      - NODE_ENV=production
    env_file:
      - ./env/.env.production
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    command: npm run start:prod
