FROM node:24-alpine

WORKDIR /usr/src/app

RUN chown -R node:node /usr/src/app
USER node

COPY --chown=node:node package.json package-lock.json ./

RUN  --mount=type=cache,target=/home/node/.npm,uid=1000,gid=1000 \
     npm ci

COPY --chown=node:node . .

EXPOSE 8080

CMD [ "npm", "run", "start:dev" ]
